[tool.poetry]
name = "meltano-tap-constant"
version = "0.1.0"
description = "A Singer SDK-based tap for constant data"
authors = ["Vo Thanh Cang <vtcanglt@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9"
singer-sdk = { version = "~=0.42.0", extras = ["faker"] }

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tap-constant = "meltano_tap_constant.tap:TapConstant.cli"