[tool.poetry]
name = "meltano-tap-constant"
version = "1.0"
description = "A Singer SDK-based tap for constant data"
authors = ["CangVo"]

[tool.poetry.dependencies]
python = ">=3.8"
singer-sdk = { version = "^0.40.0", python = "<4" }

[tool.poetry.scripts]
meltano-tap-constant = "meltano_tap_constant.tap:TapConstant.cli"
