[tool.poetry]
name="meltano-tap-constant"
version ="1.0"
description =""
authors = ["CangVo"]
keywords = []

[tool.poetry.dependencies]
python = ">3.8"
singer-sdk = { version = "^0.40.0", python = "<4" }

[tool.poetry.scripts]
tap-rest-constant = "meltano-tap-constant:TapRestConstant.cli"